In [2]:
library(tidyverse)
library(vroom)
library(data.table)
library(pheatmap)
library(preprocessCore)
library(purrr)
library(RColorBrewer)

WT_PSI <- fread("/mnt/dawnccle2/processed_data/reprocess_250221/count_normalized_v4_merged/WT_all_samples_PSI_count_table.csv")

In [3]:
count_by_PSI <- WT_PSI %>% 
    group_by(sample, index) %>%
    arrange(desc(included_count)) %>%
    slice(1) %>%
    ungroup()

# Get the top event for each index. 
top_event_by_index <- count_by_PSI %>% 
    group_by(index, offset) %>% 
    summarise(event_count = n()) %>% 
    ungroup() %>% 
    arrange(index, desc(event_count)) 

# Get major event and offset for each index.
# Get major event and offset for each index.
major_event_by_index <- top_event_by_index %>% 
    group_by(index) %>% 
    summarise( offset = offset[1], count = event_count[1]) %>% 
    ungroup() %>% 
    mutate(index_offset = paste(index, offset, sep = "__"))

`summarise()` has grouped output by 'index'. You can override using the
`.groups` argument.

ERROR: Error in `summarise()`:
ℹ In argument: `count = count[1]`.
ℹ In group 1: `index =
  "ENSG00000000003.15;TSPAN6;chrX-100632484-100632568-100630758-100630866-100633404-100633539"`.
Caused by error in `count[1]`:
! object of type 'closure' is not subsettable

In [28]:


# Write this event list to a file.
write_csv(major_event_by_index, "/mnt/dawnccle2/processed_data/reprocess_250221/count_normalized_v4_merged/WT_PSI_major_event_by_index.csv")

In [29]:
# Also write a filtered file where only the major events are kept. They are index_offset pairs. 

major_event_PSI <- WT_PSI %>% 
    mutate(index_offset = paste(index, offset, sep = "__")) %>% 
    filter(index_offset %in% major_event_by_index$index_offset)
write_csv(major_event_PSI, "/mnt/dawnccle2/processed_data/reprocess_250221/count_normalized_v4_merged/WT_all_samples_PSI_count_table_major_events.csv")

In [ ]:
# Get index with more than 2 offsets. 
index_with_more_than_2_offsets <- top_event_by_index %>% 
    group_by(index) %>% 
    summarise(n_offsets = n()) %>% 
    filter(n_offsets >= 2)

# Get the raw events for these indices. 
raw_events <- top_event_by_index %>% 
    filter(index %in% index_with_more_than_2_offsets$index) %>% 
    filter(event_count > 1)
raw_events

`summarise()` has grouped output by 'index'. You can override using the
`.groups` argument.

     index
1    ENSG00000001497.18;LAS1L;chrX-65528259-65528369-65524763-65525050-65529211-65529258
2    ENSG00000002079.14;MYH16;chr7-99285381-99285438-99284844-99284935-99287891-99288137
3    ENSG00000002079.14;MYH16;chr7-99285381-99285438-99284844-99284935-99287891-99288137
4    ENSG00000002746.15;HECW1;chr7-43508017-43508131-43507136-43507257-43508968-43509121
5    ENSG00000002746.15;HECW1;chr7-43508017-43508131-43507136-43507257-43508968-43509121
6    ENSG00000002834.18;LASP1;chr17-38898411-38898519-38878085-38878180-38914324-38914475
7    ENSG00000003096.14;KLHL13;chrX-118028423-118028497-117945433-117945575-118116507-118116865
8    ENSG00000003096.14;KLHL13;chrX-118028423-118028497-117945433-117945575-118116507-118116865
9    ENSG00000003147.19;ICA1;chr7-8143874-8143972-8127872-8128142-8158526-8158652
10   ENSG00000003147.19;ICA1;chr7-8143874-8143972-8127872-8128142-8158526-8158652
11   ENSG00000003147.19;ICA1;chr7-8235909-8235940-8232589-8232755-8262093-8262273
12   ENSG00000003147.19;ICA1;chr7-8235909-8235940-8232589-8232755-8262093-8262273
13   ENSG00000003402.20;CFLAR;chr2-201142644-201142762-201140356-201140439-201145377-201145432
14   ENSG00000003402.20;CFLAR;chr2-201142644-201142762-201140356-201140439-201145377-201145432
15   ENSG00000003509.16;NDUFAF7;chr2-37237756-37237835-37236095-37236176-37241577-37241637
16   ENSG00000004399.13;PLXND1;chr3-129566526-129566631-129565886-129566017-129567491-129567604
17   ENSG00000004399.13;PLXND1;chr3-129566526-129566631-129565886-129566017-129567491-129567604
18   ENSG00000004399.13;PLXND1;chr3-129566526-129566631-129565886-129566017-129567491-129567604
19   ENSG00000004455.17;AK2;chr1-33021366-33021461-33014364-33014594-33021592-33021690
20   ENSG00000004455.17;AK2;chr1-33021366-33021461-33014364-33014594-33021592-33021690
21   ENSG00000004455.17;AK2;chr1-33021592-33021703-33014482-33014594-33024441-33024567
22   ENSG00000004455.17;AK2;chr1-33021592-33021703-33014482-33014594-33024441-33024567
23   ENSG00000004534.15;RBM6;chr3-49972058-49972148-49962575-49962685-49975322-49975392
24   ENSG00000004534.15;RBM6;chr3-49972058-49972148-49962575-49962685-49975322-49975392
25   ENSG00000004766.17;VPS50;chr7-93296741-93296836-93294544-93294636-93297144-93297243
26   ENSG00000004766.17;VPS50;chr7-93296741-93296836-93294544-93294636-93297144-93297243
27   ENSG00000004864.14;SLC25A13;chr7-96184926-96185011-96184276-96184435-96189293-96189378
28   ENSG00000004864.14;SLC25A13;chr7-96184926-96185011-96184276-96184435-96189293-96189378
29   ENSG00000004897.12;CDC27;chr17-47151805-47151918-47143882-47143982-47154671-47154786
30   ENSG00000004897.12;CDC27;chr17-47151805-47151918-47143882-47143982-47154671-47154786
⋮    ⋮
7642 ENSG00000287526.1;AC005792.1;chr19-34003594-34003707-34000340-34000398-34061381-34061490
7643 ENSG00000287528.1;RP11-425A6.6;chr10-35644879-35644916-35644495-35644563-35646899-35647826
7644 ENSG00000287528.1;RP11-425A6.6;chr10-35644879-35644916-35644495-35644563-35646899-35647826
7645 ENSG00000287597.1;RP11-209B12.1;chr5-40308983-40309072-40306823-40308625-40312867-40312905
7646 ENSG00000287597.1;RP11-209B12.1;chr5-40308983-40309072-40306823-40308625-40312867-40312905
7647 ENSG00000287778.1;RP11-281P23.3;chr4-11434320-11434415-11429691-11433319-11438163-11438505
7648 ENSG00000287778.1;RP11-281P23.3;chr4-11434320-11434415-11429691-11433319-11438163-11438505
7649 ENSG00000287778.1;RP11-281P23.3;chr4-11434320-11434415-11429691-11433319-11438163-11438505
7650 ENSG00000287875.1;RP11-103P16.1;chr2-58041491-58041553-58040210-58041068-58046523-58046700
7651 ENSG00000287875.1;RP11-103P16.1;chr2-58041491-58041553-58040210-58041068-58046523-58046700
7652 ENSG00000288000.1;RP1-138B7.8;chr20-43534007-43534093-43533341-43533418-43534283-43534394
7653 ENSG00000288000.1;RP1-138B7.8;chr20-43534007-43534093-43533341-43533418-43534283-43534394
7654 ENSG00000288029.1;RP11-122D19.3;chr3-54055600-54055649-54052901-54053338-54056646-54058864
7655 ENSG00000288029.1;RP11-122D19.3;chr3-54055600-54055649-54052901-54053338-54056646-54058864
7656 ENSG00000288520.1;RP3-402L9.3;chr6-154223169-154223243-154221256-154221328-154246590-154246760
7657 ENSG00000288520.1;RP3-402L9.3;chr6-154247448-154247485-154246590-154246760-154265911-154265964
7658 ENSG00000288520.1;RP3-402L9.3;chr6-154247448-154247485-154246590-154246760-154265911-154265964
7659 ENSG00000288558.2;DUS4L-BCAP29;chr7-107600396-107600505-107595866-107596002-107613331-107613432
7660 ENSG00000288597.1;RP5-1055C14.9;chrX-103788409-103788505-103776346-103776653-103792680-103792738
7661 ENSG00000288597.1;RP5-1055C14.9;chrX-103788409-103788505-103776346-103776653-103792680-103792738
7662 ENSG00000288597.1;RP5-1055C14.9;chrX-103788409-103788505-103776346-103776653-103792680-103792738
7663 ENSG00000288602.1;C8orf44-SGK3;chr8-66835762-66835846-66831253-66831311-66835942-66836074
7664 ENSG00000288639.1;CTB-31E20.1;chr5-171420406-171420443-171420015-171420231-171436092-171436172
7665 ENSG00000288643.1;RP11-95I19.4;chr5-62515387-62515501-62306205-62306536-62530708-62530785
7666 ENSG00000288643.1;RP11-95I19.4;chr5-62515387-62515501-62306205-62306536-62530708-62530785
7667 ENSG00000288694.1;RP11-348N17.2;chr9-64099418-64099503-64095384-64095454-64104156-64104229
7668 ENSG00000288694.1;RP11-348N17.2;chr9-64099418-64099503-64095384-64095454-64104156-64104229
7669 ENSG00000288710.1;RP11-386G11.12;chr12-49005461-49005543-49005305-49005364-49005742-49005852
7670 ENSG00000288710.1;RP11-386G11.12;chr12-49005461-49005543-49005305-49005364-49005742-49005852
7671 ENSG00000288720.1;RP11-852E15.3;chr3-45812038-45812157-45796892-45797014-45818281-45818389
     offset     event_count
1    0:0:0      146
2    0:0:0      139
3    -31:0:0      7
4    0:0:0      144
5    0:-68:0      3
6    0:0:0      146
7    0:0:0      145
8    0:-53:0      2
9    0:0:0      144
10   -13:0:0      3
11   -65:0:0     78
12   0:0:0       68
13   0:0:0      126
14   -21:0:0     21
15   0:0:0      146
16   -44:0:0    139
17   0:0:0        6
18   -47:0:0      2
19   0:0:0      143
20   0:-4:0       4
21   0:0:0      140
22   102:0:0      7
23   0:0:0      117
24   -59:-146:0  30
25   0:0:0      123
26   0:-80:0     24
27   0:-26:0    141
28   0:0:0        6
29   0:-47:0    132
30   0:0:0       15
⋮    ⋮          ⋮
7642 0:0:0      146
7643 -5:0:0      79
7644 0:0:0       68
7645 0:0:0      145
7646 0:-2:0       2
7647 0:-53:0     82
7648 0:0:0       57
7649 0:-62:0      8
7650 0:0:0      135
7651 0:-2:0      12
7652 0:0:0      145
7653 0:-3:0       2
7654 0:0:0      124
7655 -47:0:0     23
7656 0:0:0      146
7657 -3:0:0     119
7658 0:0:0       28
7659 0:0:0      146
7660 11:0:0     124
7661 0:0:0       18
7662 0:-23:0      4
7663 0:0:0      146
7664 0:0:0      146
7665 0:0:0      144
7666 0:-90:0      3
7667 0:0:0      143
7668 0:-18:0      4
7669 0:0:0      144
7670 -49:0:0      3
7671 0:0:0      146

# ALSO DO MAJOR EVENTS FOR MUT

In [4]:
library(tidyverse)
library(vroom)
library(data.table)
library(pheatmap)
library(preprocessCore)
library(purrr)
library(RColorBrewer)

MUT_PSI <- fread("/mnt/dawnccle2/processed_data/reprocess_250221/count_normalized_v4_merged/MUT_all_samples_PSI_count_table.csv")

count_by_PSI <- MUT_PSI %>% 
    group_by(sample, index) %>%
    arrange(desc(included_count)) %>%
    slice(1) %>%
    ungroup()

# Get the top event for each index. 
top_event_by_index <- count_by_PSI %>% 
    group_by(index, offset) %>% 
    summarise(event_count = n()) %>% 
    ungroup() %>% 
    arrange(index, desc(event_count)) 

# Get major event and offset for each index.
major_event_by_index <- top_event_by_index %>% 
    group_by(index) %>% 
    summarise( offset = offset[1], count = event_count[1]) %>% 
    ungroup() %>% 
    mutate(index_offset = paste(index, offset, sep = "__"))

# Write this event list to a file.
write_csv(major_event_by_index, "/mnt/dawnccle2/processed_data/reprocess_250221/count_normalized_v4_merged/MUT_PSI_major_event_by_index.csv")

# Also write a filtered file where only the major events are kept. They are index_offset pairs. 

major_event_PSI <- MUT_PSI %>% 
    mutate(index_offset = paste(index, offset, sep = "__")) %>% 
    filter(index_offset %in% major_event_by_index$index_offset)
write_csv(major_event_PSI, "/mnt/dawnccle2/processed_data/reprocess_250221/count_normalized_v4_merged/MUT_all_samples_PSI_count_table_major_events.csv")

`summarise()` has grouped output by 'index'. You can override using the
`.groups` argument.

In [5]:
# Get index with more than 2 offsets. 
index_with_more_than_2_offsets <- top_event_by_index %>% 
    group_by(index) %>% 
    summarise(n_offsets = n()) %>% 
    filter(n_offsets >= 2)

# Get the raw events for these indices. 
raw_events <- top_event_by_index %>% 
    filter(index %in% index_with_more_than_2_offsets$index) %>% 
    filter(event_count > 1)
raw_events

     index
1    ENSG00000002079.14;MYH16;chr7-99285381-99285438-99284844-99284935-99287891-99288137
2    ENSG00000003147.19;ICA1;chr7-8235909-8235940-8232589-8232755-8262093-8262273
3    ENSG00000003147.19;ICA1;chr7-8235909-8235940-8232589-8232755-8262093-8262273
4    ENSG00000003402.20;CFLAR;chr2-201142644-201142762-201140356-201140439-201145377-201145432
5    ENSG00000003402.20;CFLAR;chr2-201142644-201142762-201140356-201140439-201145377-201145432
6    ENSG00000004399.13;PLXND1;chr3-129566526-129566631-129565886-129566017-129567491-129567604
7    ENSG00000004455.17;AK2;chr1-33021366-33021461-33014364-33014594-33021592-33021690
8    ENSG00000004455.17;AK2;chr1-33021366-33021461-33014364-33014594-33021592-33021690
9    ENSG00000004864.14;SLC25A13;chr7-96184926-96185011-96184276-96184435-96189293-96189378
10   ENSG00000004864.14;SLC25A13;chr7-96184926-96185011-96184276-96184435-96189293-96189378
11   ENSG00000005108.16;THSD7A;chr7-11460661-11460765-11447229-11447424-11462010-11462143
12   ENSG00000005108.16;THSD7A;chr7-11460661-11460765-11447229-11447424-11462010-11462143
13   ENSG00000005189.20;REXO5;chr16-20814984-20815053-20813189-20813302-20821761-20821834
14   ENSG00000005379.17;TSPOAP1;chr17-58306341-58306386-58305832-58305865-58306799-58306968
15   ENSG00000005379.17;TSPOAP1;chr17-58306341-58306386-58305832-58305865-58306799-58306968
16   ENSG00000005469.12;CROT;chr7-87382073-87382181-87381909-87381993-87382412-87382543
17   ENSG00000005469.12;CROT;chr7-87382073-87382181-87381909-87381993-87382412-87382543
18   ENSG00000005844.19;ITGAL;chr16-30475305-30475400-30474000-30474298-30479090-30479174
19   ENSG00000005844.19;ITGAL;chr16-30499372-30499489-30496435-30496566-30504174-30504264
20   ENSG00000005884.18;ITGA3;chr17-50075458-50075526-50074447-50074534-50075598-50075700
21   ENSG00000005884.18;ITGA3;chr17-50075458-50075526-50074447-50074534-50075598-50075700
22   ENSG00000006016.12;CRLF1;chr19-18594064-18594107-18593236-18593579-18594246-18594434
23   ENSG00000006016.12;CRLF1;chr19-18594064-18594107-18593236-18593579-18594246-18594434
24   ENSG00000006432.16;MAP3K9;chr14-70765441-70765487-70761001-70761182-70783222-70783445
25   ENSG00000006530.18;AGK;chr7-141615470-141615565-141614145-141614178-141621731-141621790
26   ENSG00000006530.18;AGK;chr7-141615470-141615565-141614145-141614178-141621731-141621790
27   ENSG00000006530.18;AGK;chr7-141633900-141633980-141621731-141621801-141636959-141636981
28   ENSG00000006652.15;IFRD1;chr7-112458916-112459018-112456913-112457038-112461865-112461916
29   ENSG00000006652.15;IFRD1;chr7-112458916-112459018-112456913-112457038-112461865-112461916
30   ENSG00000007312.13;CD79B;chr17-63931334-63931385-63929769-63929888-63932194-63932261
⋮    ⋮
1517 ENSG00000283930.1;PLD5P1;chr10-38095537-38095629-38094367-38094490-38095743-38095804
1518 ENSG00000284668.2;LINC02780;chr1-3995641-3995691-3976881-3977102-3995784-3995830
1519 ENSG00000284668.2;LINC02780;chr1-3995641-3995691-3976881-3977102-3995784-3995830
1520 ENSG00000284668.2;LINC02780;chr1-3996823-3996932-3976881-3977102-4012230-4012704
1521 ENSG00000284668.2;LINC02780;chr1-3996823-3996932-3976881-3977102-4012230-4012704
1522 ENSG00000284954.1;XXbac-BPG300A18.15;chr6-32153765-32153836-32152801-32153172-32154168-32154326
1523 ENSG00000284954.1;XXbac-BPG300A18.15;chr6-32153765-32153836-32152801-32153172-32154168-32154326
1524 ENSG00000285572.2;RP11-19D22.1;chr13-76835980-76836085-76729344-76729510-76846400-76846524
1525 ENSG00000285572.2;RP11-19D22.1;chr13-76835980-76836085-76729344-76729510-76846400-76846524
1526 ENSG00000285876.1;RP11-115H11.1;chr2-13182006-13182055-13000952-13001017-13270878-13270966
1527 ENSG00000285876.1;RP11-115H11.1;chr2-13182006-13182055-13000952-13001017-13270878-13270966
1528 ENSG00000285932.1;RP11-483F11.9;chr10-99679768-99679805-99677928-99678005-99691605-99691684
1529 ENSG00000285932.1;RP11-483F11.9;chr10-99679768-99679805-99677928-99678005-99691605-99691684
1530 ENSG00000286099.1;RP11-779M2.1;chr14-40889121-40889174-40885663-40885742-40901826-40905513
1531 ENSG00000286134.2;CTD-2015B23.3;chr5-24139887-24139966-24135159-24135387-24271567-24271821
1532 ENSG00000286134.2;CTD-2015B23.3;chr5-24139887-24139966-24135159-24135387-24271567-24271821
1533 ENSG00000286600.1;RP11-27G14.5;chr1-201377622-201377678-201373213-201373268-201382251-201382254
1534 ENSG00000286600.1;RP11-27G14.5;chr1-201377622-201377678-201373213-201373268-201382251-201382254
1535 ENSG00000286600.1;RP11-27G14.5;chr1-201382652-201382739-201382251-201382326-201383073-201383211
1536 ENSG00000286600.1;RP11-27G14.5;chr1-201382652-201382739-201382251-201382326-201383073-201383211
1537 ENSG00000286797.1;RP11-175O15.1;chr2-185434096-185434191-185425062-185425507-185483033-185483091
1538 ENSG00000287151.1;C2orf27A;chr2-131684708-131684819-131682474-131682557-131686063-131686211
1539 ENSG00000287151.1;C2orf27A;chr2-131684708-131684819-131682474-131682557-131686063-131686211
1540 ENSG00000287778.1;RP11-281P23.3;chr4-11434320-11434415-11429691-11433319-11438163-11438505
1541 ENSG00000287778.1;RP11-281P23.3;chr4-11434320-11434415-11429691-11433319-11438163-11438505
1542 ENSG00000287778.1;RP11-281P23.3;chr4-11434320-11434415-11429691-11433319-11438163-11438505
1543 ENSG00000288520.1;RP3-402L9.3;chr6-154247448-154247485-154246590-154246760-154265911-154265964
1544 ENSG00000288520.1;RP3-402L9.3;chr6-154247448-154247485-154246590-154246760-154265911-154265964
1545 ENSG00000288597.1;RP5-1055C14.9;chrX-103788409-103788505-103776346-103776653-103792680-103792738
1546 ENSG00000288597.1;RP5-1055C14.9;chrX-103788409-103788505-103776346-103776653-103792680-103792738
     offset  event_count
1    0:0:0   52
2    -65:0:0 44
3    0:0:0    9
4    -21:0:0 28
5    0:0:0   25
6    -44:0:0 52
7    0:0:0   51
8    0:-4:0   2
9    0:-26:0 51
10   0:0:0    2
11   0:0:0   49
12   0:-7:0   4
13   0:0:0   52
14   -27:0:0 40
15   0:0:0   13
16   0:0:0   49
17   0:-4:0   4
18   0:0:0   52
19   -35:0:0 52
20   0:0:0   51
21   -68:0:0  2
22   0:0:0   36
23   -5:0:0  17
24   0:0:0   52
25   0:0:0   47
26   0:-85:0  6
27   0:0:0   52
28   0:0:0   48
29   -56:0:0  5
30   0:0:0   48
⋮    ⋮       ⋮
1517 0:0:0   52
1518 0:0:0   51
1519 -55:0:0  2
1520 0:0:0   27
1521 -17:0:0 26
1522 0:0:0   40
1523 0:-27:0 13
1524 0:-3:0  50
1525 0:0:0    3
1526 0:0:0   51
1527 -48:0:0  2
1528 0:0:0   45
1529 -63:0:0  8
1530 0:0:0   52
1531 -20:0:0 30
1532 0:0:0   23
1533 0:0:0   41
1534 -66:0:0 12
1535 -66:0:0 30
1536 0:0:0   23
1537 0:-4:0  52
1538 0:0:0   49
1539 0:-46:0  4
1540 0:0:0   34
1541 0:-53:0 16
1542 0:-62:0  3
1543 0:0:0   33
1544 -3:0:0  20
1545 11:0:0  36
1546 0:0:0   16

# DO MAJOR EVENTS FOR A549

In [1]:
library(tidyverse)
library(vroom)
library(data.table)
library(pheatmap)
library(preprocessCore)
library(purrr)
library(RColorBrewer)

MUT_PSI <- fread("/mnt/dawnccle2/processed_data/reprocess_250221/count_normalized_v4_merged/A549_mut_all_samples_PSI_count_table.csv")

count_by_PSI <- MUT_PSI %>% 
    group_by(sample, index) %>%
    arrange(desc(included_count)) %>%
    slice(1) %>%
    ungroup()

# Get the top event for each index. 
top_event_by_index <- count_by_PSI %>% 
    group_by(index, offset) %>% 
    summarise(event_count = n()) %>% 
    ungroup() %>% 
    arrange(index, desc(event_count)) 

# Get major event and offset for each index.
major_event_by_index <- top_event_by_index %>% 
    group_by(index) %>% 
    summarise( offset = offset[1], count = event_count[1]) %>% 
    ungroup() %>% 
    mutate(index_offset = paste(index, offset, sep = "__"))

# Write this event list to a file.
write_csv(major_event_by_index, "/mnt/dawnccle2/processed_data/reprocess_250221/count_normalized_v4_merged/A549_mut_PSI_major_event_by_index.csv")

# Also write a filtered file where only the major events are kept. They are index_offset pairs. 

major_event_PSI <- MUT_PSI %>% 
    mutate(index_offset = paste(index, offset, sep = "__")) %>% 
    filter(index_offset %in% major_event_by_index$index_offset)
write_csv(major_event_PSI, "/mnt/dawnccle2/processed_data/reprocess_250221/count_normalized_v4_merged/A549_mut_all_samples_PSI_count_table_major_events.csv")

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘vroom’


The following objects are masked from ‘package:readr’:

    as.col_spec, col_character, col_date, col_datetime, col_double,
    col_factor, col_guess, col_integer, col_logical, col_number,
    col_skip, col_time, cols, cols_condense, cols_only, date_names,
    date_names_lang, date_names_langs, default_locale, fwf_cols,
    fwf_empty, fwf_positions, fwf_widths, locale, output_column,
    problems, spec



Attaching package: ‘data.table’


The following objects are masked from ‘package:lubridate’:

    hour, isoweek, mday, minute, month, quarter, second, wday, week,
    yday, year


The following objects are masked from ‘package:dplyr’:

    between, first, last


The following object is masked from ‘package:purrr’:

    transpose


`summarise()` has grouped output by 'index'. You can override using the
`.groups` argument.

# Select major alternative ss events for each: WT.

In [8]:
library(tidyverse)
library(vroom)
library(data.table)
library(pheatmap)
library(preprocessCore)
library(purrr)
library(RColorBrewer)

WT_count <- fread("/mnt/dawnccle2/processed_data/reprocess_250221/count_normalized_v4_merged/WT_all_samples_raw_counts.csv")

WT_count <- WT_count %>% 
    filter(mode != "UNSPLICED") %>%
    group_by(sample, index) %>% 
    mutate(total_count = sum(count_scaled)) %>% 
    mutate(count_perc = count_scaled / total_count) %>% 
    ungroup() 

# Get the skipped count for each sample. 
skipped_count <- WT_count %>% 
    filter(mode == "SKIPPED") %>% 
    group_by(sample, index) %>% 
    summarise(skipped_count = sum(count_scaled),
    skipped_perc = skipped_count / total_count) %>% 
    ungroup() 

# Merge the skipped count with the major event PSI. 
WT_count <- WT_count %>% 
    left_join(skipped_count, by = c("sample", "index")) %>% 
    # Set NA to 0. 
    mutate(skipped_count = ifelse(is.na(skipped_count), 0, skipped_count)) %>% 
    mutate(skipped_perc = ifelse(is.na(skipped_perc), 0, skipped_perc))

`summarise()` has grouped output by 'sample'. You can override using the
`.groups` argument.

In [16]:
WT_included <- WT_count %>% 
    filter(total_count >= 30) %>%
    filter(mode == "INCLUDED") 

# Get the major included event for each index. 
major_included_event <- WT_included %>% 
    group_by(index, offset) %>% 
    summarise(average_count_perc = mean(count_perc)) %>% 
    ungroup() %>% 
    group_by(index) %>% 
    arrange(desc(average_count_perc)) %>% 
    slice(1) %>% 
    ungroup() 

# Write this to a csv file.
write_csv(major_included_event, "/mnt/dawnccle2/processed_data/reprocess_250221/count_normalized_v4_merged/WT_included_major_event_by_index.csv")

`summarise()` has grouped output by 'index'. You can override using the
`.groups` argument.

In [ ]:
# Filter the list of events.
major_included_event_filtered <- major_included_event %>% arrange((average_count_perc)) %>% 
    filter(average_count_perc > 0.01) %>% 
    separate(offset, into = c("upstream_offset", "downstream_offset", "const_offset"), sep = ":", remove = FALSE) %>% 
    mutate(upstream_offset = as.numeric(upstream_offset),
    downstream_offset = as.numeric(downstream_offset),
    const_offset = as.numeric(const_offset)) %>% 
    filter(upstream_offset < 200 & downstream_offset < 200)

write_csv(major_included_event_filtered, "/mnt/dawnccle2/processed_data/reprocess_250221/count_normalized_v4_merged/WT_included_major_event_by_index_filtered.csv")

# For each "major event", get the list of events that are not major. Where the table will have 3 columsn: index, offset_major, offset_minor.
WT_included_index_offset <- WT_included %>% 
    mutate(index_offset = paste(index, offset, sep = "__")) %>% 
    select(index_offset, index, offset) %>% 
    distinct()

WT_major_events <- major_included_event_filtered %>% 
    mutate(index_offset = paste(index, offset, sep = "__")) %>% 
    select(index_offset, index, offset) %>% 
    distinct()

# Merge all_and_major_events. 
WT_included_all_event_pairs <- WT_major_events %>% 
    left_join(WT_included_index_offset, by = "index") %>%
    filter(index_offset.x != index_offset.y) %>% 
    rename(index_offset_major = index_offset.x, index_offset_minor = index_offset.y) %>% 
    rename(offset_major = offset.x, offset_minor = offset.y)

write_csv(WT_included_all_event_pairs, "/mnt/dawnccle2/processed_data/reprocess_250221/count_normalized_v4_merged/WT_included_all_unique_event_pairs.csv")

# Select major events for each: MUT.

In [46]:
library(tidyverse)
library(vroom)
library(data.table)
library(pheatmap)
library(preprocessCore)
library(purrr)
library(RColorBrewer)

MUT_count <- fread("/mnt/dawnccle2/processed_data/reprocess_250221/count_normalized_v4_merged/MUT_all_samples_raw_counts.csv")

MUT_count <- MUT_count %>% 
    filter(mode != "UNSPLICED") %>%
    group_by(sample, index) %>% 
    mutate(total_count = sum(count_scaled)) %>% 
    mutate(count_perc = count_scaled / total_count) %>% 
    ungroup() 

# Get the skipped count for each sample. 
skipped_count <- MUT_count %>% 
    filter(mode == "SKIPPED") %>% 
    group_by(sample, index) %>% 
    summarise(skipped_count = sum(count_scaled),
    skipped_perc = skipped_count / total_count) %>% 
    ungroup() 

# Merge the skipped count with the major event PSI. 
MUT_count <- MUT_count %>% 
    left_join(skipped_count, by = c("sample", "index")) %>% 
    # Set NA to 0. 
    mutate(skipped_count = ifelse(is.na(skipped_count), 0, skipped_count)) %>% 
    mutate(skipped_perc = ifelse(is.na(skipped_perc), 0, skipped_perc))

In [ ]:
MUT_included <- MUT_count %>% 
    filter(total_count >= 30) %>%
    filter(mode == "INCLUDED") 

# Get the major included event for each index. 
major_included_event <- MUT_included %>% 
    group_by(index, offset) %>% 
    summarise(average_count_perc = mean(count_perc)) %>% 
    ungroup() %>% 
    group_by(index) %>% 
    arrange(desc(average_count_perc)) %>% 
    slice(1) %>% 
    ungroup() 

# Write this to a csv file.
write_csv(major_included_event, "/mnt/dawnccle2/processed_data/reprocess_250221/count_normalized_v4_merged/MUT_included_major_event_by_index.csv")

# Filter the list of events.
major_included_event_filtered <- major_included_event %>% arrange((average_count_perc)) %>% 
    filter(average_count_perc > 0.01) %>% 
    separate(offset, into = c("upstream_offset", "downstream_offset", "const_offset"), sep = ":", remove = FALSE) %>% 
    mutate(upstream_offset = as.numeric(upstream_offset),
    downstream_offset = as.numeric(downstream_offset),
    const_offset = as.numeric(const_offset)) %>% 
    filter(upstream_offset < 200 & downstream_offset < 200)

write_csv(major_included_event_filtered, "/mnt/dawnccle2/processed_data/reprocess_250221/count_normalized_v4_merged/MUT_included_major_event_by_index_filtered.csv")

# For each "major event", get the list of events that are not major. Where the table will have 3 columsn: index, offset_major, offset_minor.
MUT_included_index_offset <- MUT_included %>% 
    mutate(index_offset = paste(index, offset, sep = "__")) %>% 
    select(index_offset, index, offset) %>% 
    distinct()

MUT_major_events <- major_included_event_filtered %>% 
    mutate(index_offset = paste(index, offset, sep = "__")) %>% 
    select(index_offset, index, offset) %>% 
    distinct()

# Merge all_and_major_events. 
MUT_included_all_event_pairs <- MUT_major_events %>% 
    left_join(MUT_included_index_offset, by = "index") %>%
    filter(index_offset.x != index_offset.y) %>% 
    rename(index_offset_major = index_offset.x, index_offset_minor = index_offset.y) %>% 
    rename(offset_major = offset.x, offset_minor = offset.y)

write_csv(MUT_included_all_event_pairs, "/mnt/dawnccle2/processed_data/reprocess_250221/count_normalized_v4_merged/MUT_included_all_unique_event_pairs.csv")

       index_offset_major
1      ENSG00000118193.12;KIF14;chr1-200593666-200593769-200592079-200592240-200598236-200598421__0:0:0
2      ENSG00000118193.12;KIF14;chr1-200593666-200593769-200592079-200592240-200598236-200598421__0:0:0
3      ENSG00000118193.12;KIF14;chr1-200593666-200593769-200592079-200592240-200598236-200598421__0:0:0
4      ENSG00000118193.12;KIF14;chr1-200593666-200593769-200592079-200592240-200598236-200598421__0:0:0
5      ENSG00000118193.12;KIF14;chr1-200593666-200593769-200592079-200592240-200598236-200598421__0:0:0
6      ENSG00000118193.12;KIF14;chr1-200593666-200593769-200592079-200592240-200598236-200598421__0:0:0
7      ENSG00000118193.12;KIF14;chr1-200593666-200593769-200592079-200592240-200598236-200598421__0:0:0
8      ENSG00000197283.18;SYNGAP1;chr6-33442452-33442494-33441580-33441759-33442888-33443960__0:0:0
9      ENSG00000197283.18;SYNGAP1;chr6-33442452-33442494-33441580-33441759-33442888-33443960__0:0:0
10     ENSG00000197283.18;SYNGAP1;chr6-33442452-33442494-33441580-33441759-33442888-33443960__0:0:0
11     ENSG00000197283.18;SYNGAP1;chr6-33442452-33442494-33441580-33441759-33442888-33443960__0:0:0
12     ENSG00000197283.18;SYNGAP1;chr6-33442452-33442494-33441580-33441759-33442888-33443960__0:0:0
13     ENSG00000197283.18;SYNGAP1;chr6-33442452-33442494-33441580-33441759-33442888-33443960__0:0:0
14     ENSG00000197283.18;SYNGAP1;chr6-33442452-33442494-33441580-33441759-33442888-33443960__0:0:0
15     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__0:0:0
16     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__0:0:0
17     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__0:0:0
18     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__0:0:0
19     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__0:0:0
20     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__0:0:0
21     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__0:0:0
22     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__0:0:0
23     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__0:0:0
24     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__0:0:0
25     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__0:0:0
26     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__0:0:0
27     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__0:0:0
28     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__0:0:0
29     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__0:0:0
30     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__0:0:0
⋮      ⋮
414756 ENSG00000143850.16;PLEKHA6;chr1-204267474-204267547-204264941-204265042-204268207-204268312__0:-1:0
414757 ENSG00000143850.16;PLEKHA6;chr1-204267474-204267547-204264941-204265042-204268207-204268312__0:-1:0
414758 ENSG00000143850.16;PLEKHA6;chr1-204267474-204267547-204264941-204265042-204268207-204268312__0:-1:0
414759 ENSG00000162643.13;DNAI3;chr1-85121750-85121814-85117728-85117859-85124120-85124251__0:1:0
414760 ENSG00000162643.13;DNAI3;chr1-85121750-85121814-85117728-85117859-85124120-85124251__0:1:0
414761 ENSG00000162643.13;DNAI3;chr1-85121750-85121814-85117728-85117859-85124120-85124251__0:1:0
414762 ENSG00000162643.13;DNAI3;chr1-85121750-85121814-85117728-85117859-85124120-85124251__0:1:0
414763 ENSG00000162643.13;DNAI3;chr1-85121750-85121814-85117728-85117859-85124120-85124251__0:1:0
414764 ENSG00000162643.13;DNAI3;chr1-85121750-85121814-85117728-85117859-85124120-85124251__0:1:0
414765 ENSG00000162643.13;DNAI3;chr1-85121750-85121814-85117728-85117859-85124120-85124251__0:1:0
414766 ENSG00000162643.13;DNAI3;chr1-85121750-85121814-85117728-85117859-85124120-85124251__0:1:0
414767 ENSG00000162643.13;DNAI3;chr1-85121750-85121814-85117728-85117859-85124120-85124251__0:1:0
414768 ENSG00000167302.11;TEPSIN;chr17-81233637-81233716-81233431-81233503-81233980-81234048__1:0:0
414769 ENSG00000167302.11;TEPSIN;chr17-81233637-81233716-81233431-81233503-81233980-81234048__1:0:0
414770 ENSG00000167302.11;TEPSIN;chr17-81233637-81233716-81233431-81233503-81233980-81234048__1:0:0
414771 ENSG00000167302.11;TEPSIN;chr17-81233637-81233716-81233431-81233503-81233980-81234048__1:0:0
414772 ENSG00000167302.11;TEPSIN;chr17-81233637-81233716-81233431-81233503-81233980-81234048__1:0:0
414773 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451__0:-1:0
414774 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451__0:-1:0
414775 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451__0:-1:0
414776 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451__0:-1:0
414777 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451__0:-1:0
414778 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451__0:-1:0
414779 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451__0:-1:0
414780 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451__0:-1:0
414781 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451__0:-1:0
414782 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451__0:-1:0
414783 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451__0:-1:0
414784 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451__0:-1:0
414785 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451__0:-1:0
       index
1      ENSG00000118193.12;KIF14;chr1-200593666-200593769-200592079-200592240-200598236-200598421
2      ENSG00000118193.12;KIF14;chr1-200593666-200593769-200592079-200592240-200598236-200598421
3      ENSG00000118193.12;KIF14;chr1-200593666-200593769-200592079-200592240-200598236-200598421
4      ENSG00000118193.12;KIF14;chr1-200593666-200593769-200592079-200592240-200598236-200598421
5      ENSG00000118193.12;KIF14;chr1-200593666-200593769-200592079-200592240-200598236-200598421
6      ENSG00000118193.12;KIF14;chr1-200593666-200593769-200592079-200592240-200598236-200598421
7      ENSG00000118193.12;KIF14;chr1-200593666-200593769-200592079-200592240-200598236-200598421
8      ENSG00000197283.18;SYNGAP1;chr6-33442452-33442494-33441580-33441759-33442888-33443960
9      ENSG00000197283.18;SYNGAP1;chr6-33442452-33442494-33441580-33441759-33442888-33443960
10     ENSG00000197283.18;SYNGAP1;chr6-33442452-33442494-33441580-33441759-33442888-33443960
11     ENSG00000197283.18;SYNGAP1;chr6-33442452-33442494-33441580-33441759-33442888-33443960
12     ENSG00000197283.18;SYNGAP1;chr6-33442452-33442494-33441580-33441759-33442888-33443960
13     ENSG00000197283.18;SYNGAP1;chr6-33442452-33442494-33441580-33441759-33442888-33443960
14     ENSG00000197283.18;SYNGAP1;chr6-33442452-33442494-33441580-33441759-33442888-33443960
15     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378
16     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378
17     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378
18     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378
19     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378
20     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378
21     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378
22     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378
23     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378
24     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378
25     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378
26     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378
27     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378
28     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378
29     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378
30     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378
⋮      ⋮
414756 ENSG00000143850.16;PLEKHA6;chr1-204267474-204267547-204264941-204265042-204268207-204268312
414757 ENSG00000143850.16;PLEKHA6;chr1-204267474-204267547-204264941-204265042-204268207-204268312
414758 ENSG00000143850.16;PLEKHA6;chr1-204267474-204267547-204264941-204265042-204268207-204268312
414759 ENSG00000162643.13;DNAI3;chr1-85121750-85121814-85117728-85117859-85124120-85124251
414760 ENSG00000162643.13;DNAI3;chr1-85121750-85121814-85117728-85117859-85124120-85124251
414761 ENSG00000162643.13;DNAI3;chr1-85121750-85121814-85117728-85117859-85124120-85124251
414762 ENSG00000162643.13;DNAI3;chr1-85121750-85121814-85117728-85117859-85124120-85124251
414763 ENSG00000162643.13;DNAI3;chr1-85121750-85121814-85117728-85117859-85124120-85124251
414764 ENSG00000162643.13;DNAI3;chr1-85121750-85121814-85117728-85117859-85124120-85124251
414765 ENSG00000162643.13;DNAI3;chr1-85121750-85121814-85117728-85117859-85124120-85124251
414766 ENSG00000162643.13;DNAI3;chr1-85121750-85121814-85117728-85117859-85124120-85124251
414767 ENSG00000162643.13;DNAI3;chr1-85121750-85121814-85117728-85117859-85124120-85124251
414768 ENSG00000167302.11;TEPSIN;chr17-81233637-81233716-81233431-81233503-81233980-81234048
414769 ENSG00000167302.11;TEPSIN;chr17-81233637-81233716-81233431-81233503-81233980-81234048
414770 ENSG00000167302.11;TEPSIN;chr17-81233637-81233716-81233431-81233503-81233980-81234048
414771 ENSG00000167302.11;TEPSIN;chr17-81233637-81233716-81233431-81233503-81233980-81234048
414772 ENSG00000167302.11;TEPSIN;chr17-81233637-81233716-81233431-81233503-81233980-81234048
414773 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451
414774 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451
414775 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451
414776 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451
414777 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451
414778 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451
414779 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451
414780 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451
414781 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451
414782 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451
414783 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451
414784 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451
414785 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451
       offset_major
1      0:0:0
2      0:0:0
3      0:0:0
4      0:0:0
5      0:0:0
6      0:0:0
7      0:0:0
8      0:0:0
9      0:0:0
10     0:0:0
11     0:0:0
12     0:0:0
13     0:0:0
14     0:0:0
15     0:0:0
16     0:0:0
17     0:0:0
18     0:0:0
19     0:0:0
20     0:0:0
21     0:0:0
22     0:0:0
23     0:0:0
24     0:0:0
25     0:0:0
26     0:0:0
27     0:0:0
28     0:0:0
29     0:0:0
30     0:0:0
⋮      ⋮
414756 0:-1:0
414757 0:-1:0
414758 0:-1:0
414759 0:1:0
414760 0:1:0
414761 0:1:0
414762 0:1:0
414763 0:1:0
414764 0:1:0
414765 0:1:0
414766 0:1:0
414767 0:1:0
414768 1:0:0
414769 1:0:0
414770 1:0:0
414771 1:0:0
414772 1:0:0
414773 0:-1:0
414774 0:-1:0
414775 0:-1:0
414776 0:-1:0
414777 0:-1:0
414778 0:-1:0
414779 0:-1:0
414780 0:-1:0
414781 0:-1:0
414782 0:-1:0
414783 0:-1:0
414784 0:-1:0
414785 0:-1:0
       index_offset_minor
1      ENSG00000118193.12;KIF14;chr1-200593666-200593769-200592079-200592240-200598236-200598421__357:298:0
2      ENSG00000118193.12;KIF14;chr1-200593666-200593769-200592079-200592240-200598236-200598421__0:-78:0
3      ENSG00000118193.12;KIF14;chr1-200593666-200593769-200592079-200592240-200598236-200598421__275:298:0
4      ENSG00000118193.12;KIF14;chr1-200593666-200593769-200592079-200592240-200598236-200598421__378:298:0
5      ENSG00000118193.12;KIF14;chr1-200593666-200593769-200592079-200592240-200598236-200598421__132:33:0
6      ENSG00000118193.12;KIF14;chr1-200593666-200593769-200592079-200592240-200598236-200598421__377:298:0
7      ENSG00000118193.12;KIF14;chr1-200593666-200593769-200592079-200592240-200598236-200598421__-5:-103:0
8      ENSG00000197283.18;SYNGAP1;chr6-33442452-33442494-33441580-33441759-33442888-33443960__327:329:0
9      ENSG00000197283.18;SYNGAP1;chr6-33442452-33442494-33441580-33441759-33442888-33443960__348:329:0
10     ENSG00000197283.18;SYNGAP1;chr6-33442452-33442494-33441580-33441759-33442888-33443960__16:0:0
11     ENSG00000197283.18;SYNGAP1;chr6-33442452-33442494-33441580-33441759-33442888-33443960__122:83:0
12     ENSG00000197283.18;SYNGAP1;chr6-33442452-33442494-33441580-33441759-33442888-33443960__0:-1:0
13     ENSG00000197283.18;SYNGAP1;chr6-33442452-33442494-33441580-33441759-33442888-33443960__316:329:0
14     ENSG00000197283.18;SYNGAP1;chr6-33442452-33442494-33441580-33441759-33442888-33443960__36:-3:0
15     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__316:339:0
16     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__337:339:0
17     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__10:0:0
18     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__-11:0:0
19     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__-2:0:0
20     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__319:303:0
21     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__348:339:0
22     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__119:103:0
23     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__316:338:0
24     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__316:322:0
25     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__9:-9:0
26     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__229:213:0
27     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__0:5:0
28     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__354:339:0
29     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__229:339:0
30     ENSG00000106278.12;PTPRZ1;chr7-122034094-122034115-122031473-122031559-122034281-122034378__-99:0:0
⋮      ⋮
414756 ENSG00000143850.16;PLEKHA6;chr1-204267474-204267547-204264941-204265042-204268207-204268312__0:-38:0
414757 ENSG00000143850.16;PLEKHA6;chr1-204267474-204267547-204264941-204265042-204268207-204268312__0:-11:0
414758 ENSG00000143850.16;PLEKHA6;chr1-204267474-204267547-204264941-204265042-204268207-204268312__0:-8:0
414759 ENSG00000162643.13;DNAI3;chr1-85121750-85121814-85117728-85117859-85124120-85124251__0:0:0
414760 ENSG00000162643.13;DNAI3;chr1-85121750-85121814-85117728-85117859-85124120-85124251__-19:0:0
414761 ENSG00000162643.13;DNAI3;chr1-85121750-85121814-85117728-85117859-85124120-85124251__0:-4:0
414762 ENSG00000162643.13;DNAI3;chr1-85121750-85121814-85117728-85117859-85124120-85124251__-2:0:0
414763 ENSG00000162643.13;DNAI3;chr1-85121750-85121814-85117728-85117859-85124120-85124251__4:0:0
414764 ENSG00000162643.13;DNAI3;chr1-85121750-85121814-85117728-85117859-85124120-85124251__0:4:0
414765 ENSG00000162643.13;DNAI3;chr1-85121750-85121814-85117728-85117859-85124120-85124251__0:-2:0
414766 ENSG00000162643.13;DNAI3;chr1-85121750-85121814-85117728-85117859-85124120-85124251__-84:-143:0
414767 ENSG00000162643.13;DNAI3;chr1-85121750-85121814-85117728-85117859-85124120-85124251__359:318:0
414768 ENSG00000167302.11;TEPSIN;chr17-81233637-81233716-81233431-81233503-81233980-81234048__0:0:0
414769 ENSG00000167302.11;TEPSIN;chr17-81233637-81233716-81233431-81233503-81233980-81234048__-2:0:0
414770 ENSG00000167302.11;TEPSIN;chr17-81233637-81233716-81233431-81233503-81233980-81234048__0:4:0
414771 ENSG00000167302.11;TEPSIN;chr17-81233637-81233716-81233431-81233503-81233980-81234048__138:63:0
414772 ENSG00000167302.11;TEPSIN;chr17-81233637-81233716-81233431-81233503-81233980-81234048__-57:0:0
414773 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451__0:0:0
414774 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451__0:11:0
414775 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451__0:-14:0
414776 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451__87:0:0
414777 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451__93:0:0
414778 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451__112:11:0
414779 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451__0:-2:0
414780 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451__0:29:0
414781 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451__-2:0:0
414782 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451__81:-1:0
414783 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451__0:-3:0
414784 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451__-29:0:0
414785 ENSG00000175984.15;DENND2C;chr1-114594472-114594578-114587715-114587952-114599273-114599451__-32:-135:0
       offset_minor
1      357:298:0
2      0:-78:0
3      275:298:0
4      378:298:0
5      132:33:0
6      377:298:0
7      -5:-103:0
8      327:329:0
9      348:329:0
10     16:0:0
11     122:83:0
12     0:-1:0
13     316:329:0
14     36:-3:0
15     316:339:0
16     337:339:0
17     10:0:0
18     -11:0:0
19     -2:0:0
20     319:303:0
21     348:339:0
22     119:103:0
23     316:338:0
24     316:322:0
25     9:-9:0
26     229:213:0
27     0:5:0
28     354:339:0
29     229:339:0
30     -99:0:0
⋮      ⋮
414756 0:-38:0
414757 0:-11:0
414758 0:-8:0
414759 0:0:0
414760 -19:0:0
414761 0:-4:0
414762 -2:0:0
414763 4:0:0
414764 0:4:0
414765 0:-2:0
414766 -84:-143:0
414767 359:318:0
414768 0:0:0
414769 -2:0:0
414770 0:4:0
414771 138:63:0
414772 -57:0:0
414773 0:0:0
414774 0:11:0